"""
Library Server — a standalone MCP (Model Context Protocol) server.

Models a library of 10,000 books across seven genres (christian, politics,
history, economics, sorcery, science, sports): searching, checking copy
availability, and borrowing/returning books on behalf of members. Built
with FastMCP, the high-level Python SDK for MCP servers.

The catalog itself lives in books.json (generated by generate_books.py) and
is loaded once at startup — keeping data separate from server logic makes it
easy to regenerate or swap in a real catalog later without touching this file.

Run it directly for local dev/testing:
    python app.py

Inspect it (schema + counts) without a client:
    fastmcp inspect app.py

Run it under the MCP Inspector (interactive browser UI):
    fastmcp dev app.py
"""

import json
import os
from pathlib import Path
from typing import Optional

from mcp.server.fastmcp import FastMCP

# Hosts like Render/Railway assign the port dynamically via the PORT env
# var and require binding to 0.0.0.0 (not localhost/127.0.0.1) so the
# service is reachable from outside the container. Falls back to
# 0.0.0.0:8001 for local dev, which still works fine at
# http://localhost:8001/mcp.
PORT = int(os.environ.get("PORT", 8001))
mcp = FastMCP("Library Server", host="0.0.0.0", port=PORT)


# ---------------------------------------------------------------------------
# Catalog data — loaded once at startup from books.json
# ---------------------------------------------------------------------------

CATALOG_PATH = Path(__file__).parent / "books.json"

with open(CATALOG_PATH, "r", encoding="utf-8") as f:
    BOOKS: dict[str, dict] = json.load(f)

GENRES = sorted({b["genre"] for b in BOOKS.values()})

# Borrow history, keyed by member_id. Each entry is appended to on
# borrow_book and updated in place (return date filled) on return_book.
MEMBER_HISTORY: dict[str, list[dict]] = {
    "M001": [],
    "M002": [],
}

LIBRARY_HOURS = (
    "Monday–Friday: 9:00 AM – 8:00 PM\n"
    "Saturday: 10:00 AM – 6:00 PM\n"
    "Sunday: Closed"
)

MAX_SEARCH_RESULTS = 25  # keep responses to the model bounded on a 10k-book catalog


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

@mcp.tool()
def search_books(query: str = "", genre: Optional[str] = None) -> str:
    """
    Search the 10,000-book library catalog by title, author, or theme
    (case-insensitive, partial match), optionally narrowed to one genre.
    Use this whenever the user wants to find books, browse by topic, or look
    up an author's work, before doing anything else — you'll need the ISBN
    from these results to check availability or borrow a book.

    With a catalog this large, always pass `genre` when the user's request
    implies one (e.g. "sports books", "something on economics") — it's far
    more precise than a free-text guess. Call list_genres first if you're
    unsure which genre value to use. Results are capped at 25 matches; if
    nothing useful comes back, tell the user rather than guessing further.

    Args:
        query: A title, partial title, author name, or theme keyword to search for. Leave empty to browse a genre.
        genre: Optional exact genre to filter by — one of: christian, politics, history, economics, sorcery, science, sports.

    Returns:
        A newline-separated list of matching books (title, author, ISBN,
        genre, copies available), or a message saying nothing matched.
    """
    q = query.strip().lower()
    g = genre.strip().lower() if genre else None

    if g and g not in GENRES:
        return f"Error: unknown genre '{genre}'. Valid genres: {', '.join(GENRES)}."

    if not q and not g:
        return "Please provide a search term and/or a genre to narrow the results."

    matches = []
    for b in BOOKS.values():
        if g and b["genre"] != g:
            continue
        if q and not (
            q in b["title"].lower()
            or q in b["author"].lower()
            or any(q in tag for tag in b["tags"])
        ):
            continue
        matches.append(b)
        if len(matches) >= MAX_SEARCH_RESULTS:
            break

    if not matches:
        scope = f" in genre '{g}'" if g else ""
        return f"No books found matching '{query}'{scope}."

    lines = [
        f"{b['title']} by {b['author']} — ISBN {b['isbn']} — {b['genre']} — {b['available_copies']} copies available"
        for b in matches
    ]
    suffix = f"\n(showing first {MAX_SEARCH_RESULTS} matches)" if len(matches) >= MAX_SEARCH_RESULTS else ""
    return "\n".join(lines) + suffix


@mcp.tool()
def list_genres() -> str:
    """
    Lists every genre available in the catalog, with a book count for each.
    Call this when the user asks what's available, or before calling
    search_books with a `genre` filter if you're not sure of the exact
    genre string to use.

    Returns:
        A newline-separated list of "genre: count" entries.
    """
    from collections import Counter
    counts = Counter(b["genre"] for b in BOOKS.values())
    lines = [f"{g}: {counts[g]} books" for g in GENRES]
    return "\n".join(lines)


@mcp.tool()
def check_availability(isbn: str) -> str:
    """
    Check how many copies of a specific book are currently available to
    borrow. Use this after search_books has given you an ISBN, or whenever
    the user asks if a specific book is in stock — always check this before
    calling borrow_book so you can tell the user up front if none are left.

    Args:
        isbn: The ISBN of the book to check, exactly as returned by search_books.

    Returns:
        A string stating the title and number of available copies, or an
        error string if the ISBN isn't in the catalog.
    """
    book = BOOKS.get(isbn)
    if not book:
        return f"Error: no book found with ISBN '{isbn}'."

    if book["available_copies"] <= 0:
        return f"'{book['title']}' has no copies available right now."
    return f"'{book['title']}' has {book['available_copies']} copies available."


@mcp.tool()
def borrow_book(isbn: str, member_id: str) -> str:
    """
    Borrows a copy of a book on behalf of a library member, decrementing its
    available copy count by one and recording it in that member's borrow
    history. Only call this after confirming with check_availability (or a
    recent search_books result) that at least one copy is available — if
    none are left, this returns an error string rather than raising, so
    always check the return value before telling the user it succeeded.

    Args:
        isbn: The ISBN of the book to borrow.
        member_id: The library member's ID, e.g. 'M001'.

    Returns:
        A confirmation string on success, or an error string if the ISBN
        doesn't exist or no copies are currently available.
    """
    book = BOOKS.get(isbn)
    if not book:
        return f"Error: no book found with ISBN '{isbn}'."

    if book["available_copies"] <= 0:
        return f"Error: no copies of '{book['title']}' are currently available to borrow."

    book["available_copies"] -= 1
    MEMBER_HISTORY.setdefault(member_id, []).append(
        {"isbn": isbn, "title": book["title"], "status": "borrowed"}
    )
    return (
        f"'{book['title']}' borrowed successfully by member {member_id}. "
        f"{book['available_copies']} copies remaining."
    )


@mcp.tool()
def return_book(isbn: str, member_id: str) -> str:
    """
    Returns a previously borrowed book on behalf of a member, incrementing
    its available copy count by one and marking the corresponding entry in
    that member's borrow history as returned. Use this when a user says
    they're bringing a book back or wants to return something they borrowed.

    Args:
        isbn: The ISBN of the book being returned.
        member_id: The library member's ID, e.g. 'M001'.

    Returns:
        A confirmation string on success, or an error string if the ISBN
        doesn't exist or this member has no matching active loan on record.
    """
    book = BOOKS.get(isbn)
    if not book:
        return f"Error: no book found with ISBN '{isbn}'."

    history = MEMBER_HISTORY.get(member_id, [])
    loan = next(
        (h for h in reversed(history) if h["isbn"] == isbn and h["status"] == "borrowed"),
        None,
    )
    if loan is None:
        return f"Error: member {member_id} has no active loan for '{book['title']}' on record."

    loan["status"] = "returned"
    book["available_copies"] += 1
    return (
        f"'{book['title']}' returned successfully by member {member_id}. "
        f"{book['available_copies']} copies now available."
    )


# ---------------------------------------------------------------------------
# Resources
# ---------------------------------------------------------------------------

@mcp.resource("library://info/hours")
def get_hours() -> str:
    """Static resource: the library's weekly operating hours."""
    return LIBRARY_HOURS


@mcp.resource("library://info/genres")
def get_genres_resource() -> str:
    """Static resource: every genre in the catalog with its book count."""
    return list_genres()


@mcp.resource("member://{member_id}/history")
def get_member_history(member_id: str) -> str:
    """Dynamic resource template: a specific member's borrow history."""
    history = MEMBER_HISTORY.get(member_id)
    if history is None:
        return f"No record found for member '{member_id}'."
    if not history:
        return f"Member {member_id} has no borrow history yet."

    lines = [f"{h['title']} — {h['status']}" for h in history]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

@mcp.prompt()
def recommend_books(genre: str, mood: Optional[str] = None) -> str:
    """Generates a reusable prompt template for recommending books by genre and mood."""
    mood_clause = f" that would suit a '{mood}' mood" if mood else ""
    return (
        f"Recommend 3 books in the '{genre}' genre{mood_clause}. "
        "For each, use search_books with the genre filter to confirm it's "
        "actually in the library catalog before recommending it, and "
        "mention whether copies are currently available."
    )


if __name__ == "__main__":
    print(f"Loaded {len(BOOKS)} books across {len(GENRES)} genres: {', '.join(GENRES)}")
    mcp.run(transport="streamable-http")
